# For standard Spring Boot parameters see:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
server:
  port: 8081
  servlet:
    session:
      timeout: 1000


# Spring Cloud Sleuth tracing extra fields to propagate (HTTP/Rest and messaging). Don't capitalize the keys
spring:  
  sleuth:
    propagation-keys:
    - x-installation-number 
    log:
      slf4j:
        whitelisted-mdc-keys:  
        - x-installation-number